import React, { useEffect, useMemo, useState } from "react";
import {
  useCurrentFrame,
  useVideoConfig,
  interpolate,
  spring,
  Img,
  staticFile,
  continueRender,
  delayRender,
} from "remotion";
import { useAudioData, visualizeAudio } from "@remotion/media-utils";

// ─────────────────────────────────────────────────────────────────────────────
// Host — the fixed HonestStack brand mascot.
//
// Two modes:
//   1. IDLE-TALK (default): the two-frame Pharaoh (mouth-closed / mouth-open),
//      audio-driven mouth swap, glides slowly across the lower band. This is
//      what every segment defaults to when no pharaoh_pose is set.
//
//   2. POSE: when the segment carries a pharaoh_pose, the Pharaoh swaps to
//      the matching pose PNG from the pose library (generated by
//      generate-pharaoh-poses via Gemini I2I, same character identity across
//      all poses). Each pose has its own anchor + entry animation so the
//      Pharaoh "peeks", "points", "celebrates" etc. into the scene with intent.
//
// All Pharaoh PNGs are on solid white backgrounds (Gemini doesn't reliably
// emit true alpha) — the WhiteKeyImage component knocks the white out to
// transparency once per asset and memoises the result.
// ─────────────────────────────────────────────────────────────────────────────

// Bundled mascot frames — fixed, identical in every render (idle-talk mode).
const PHARAOH_CLOSED = staticFile("pharaoh-closed.png");
const PHARAOH_OPEN = staticFile("pharaoh-open.png");

// Pose library — staticFile-loaded from public/poses/. Each PNG was
// generated by generate-pharaoh-poses with the original mascot as reference,
// so character identity is preserved across the set. Keep these IDs in sync
// with the editorial brain's pharaoh_pose enum.
export type PharaohPose =
  | "idle-talk"
  | "peek-left"
  | "peek-right"
  | "point-up-right"
  | "point-down"
  | "surprised"
  | "sarcastic-shrug"
  | "count-fingers"
  | "walk-in-left"
  | "walk-out-right"
  | "crying"
  | "celebrating";

// Per-pose render config.
//   src       — path to pose PNG (null = use idle-talk two-frame system)
//   anchor    — where the Pharaoh sits in the lower band
//   animation — how it enters the frame
//   scaleMul  — multiplier on the base CHAR_HEIGHT (some poses need to be
//               bigger — peeks/celebrating — others fit standard size)
//   facing    — overrides facing (1 = right, -1 = left). null = no override.
interface PosePreset {
  src: string | null;
  anchor: "glide" | "bottom-left" | "bottom-center" | "bottom-right" |
    "edge-left" | "edge-right";
  animation: "glide" | "slide-from-left" | "slide-from-right" |
    "walk-from-left" | "walk-out-right" | "fade-in" | "scale-pop";
  scaleMul: number;
  facing: 1 | -1 | null;
}

const POSE_PRESETS: Record<PharaohPose, PosePreset> = {
  "idle-talk": {
    src: null, // uses the mouth-swap two-frame system
    anchor: "glide",
    animation: "glide",
    scaleMul: 1.0,
    facing: null,
  },
  "peek-left": {
    src: staticFile("poses/peek-left.png"),
    anchor: "edge-left",
    animation: "slide-from-left",
    scaleMul: 1.15,
    facing: 1,
  },
  "peek-right": {
    src: staticFile("poses/peek-right.png"),
    anchor: "edge-right",
    animation: "slide-from-right",
    scaleMul: 1.15,
    facing: -1,
  },
  "point-up-right": {
    src: staticFile("poses/point-up-right.png"),
    anchor: "bottom-right",
    animation: "fade-in",
    scaleMul: 1.05,
    facing: null,
  },
  "point-down": {
    src: staticFile("poses/point-down.png"),
    anchor: "bottom-center",
    animation: "scale-pop",
    scaleMul: 1.1,
    facing: null,
  },
  "surprised": {
    src: staticFile("poses/surprised.png"),
    anchor: "bottom-right",
    animation: "scale-pop",
    scaleMul: 1.2,
    facing: null,
  },
  "sarcastic-shrug": {
    src: staticFile("poses/sarcastic-shrug.png"),
    anchor: "bottom-right",
    animation: "fade-in",
    scaleMul: 1.05,
    facing: null,
  },
  "count-fingers": {
    src: staticFile("poses/count-fingers.png"),
    anchor: "bottom-center",
    animation: "scale-pop",
    scaleMul: 1.05,
    facing: null,
  },
  "walk-in-left": {
    src: staticFile("poses/walk-in-left.png"),
    anchor: "bottom-left",
    animation: "walk-from-left",
    scaleMul: 1.0,
    facing: null,
  },
  "walk-out-right": {
    src: staticFile("poses/walk-out-right.png"),
    anchor: "bottom-right",
    animation: "walk-out-right",
    scaleMul: 1.0,
    facing: null,
  },
  "crying": {
    src: staticFile("poses/crying.png"),
    anchor: "bottom-center",
    animation: "fade-in",
    scaleMul: 1.1,
    facing: null,
  },
  "celebrating": {
    src: staticFile("poses/celebrating.png"),
    anchor: "bottom-center",
    animation: "scale-pop",
    scaleMul: 1.2,
    facing: null,
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// whiteKey — module-level cache of white-background → transparent data URLs.
// ─────────────────────────────────────────────────────────────────────────────
const whiteCache = new Map<string, string>();

function isWhiteBg(r: number, g: number, b: number): boolean {
  return r > 238 && g > 238 && b > 238;
}

function keyOutWhite(img: HTMLImageElement): string {
  const canvas = document.createElement("canvas");
  canvas.width = img.naturalWidth || img.width;
  canvas.height = img.naturalHeight || img.height;
  const ctx = canvas.getContext("2d");
  if (!ctx) return img.src;
  ctx.drawImage(img, 0, 0);
  const data = ctx.getImageData(0, 0, canvas.width, canvas.height);
  const px = data.data;
  for (let i = 0; i < px.length; i += 4) {
    const r = px[i], g = px[i + 1], b = px[i + 2];
    if (isWhiteBg(r, g, b)) {
      px[i + 3] = 0;
    } else if (r > 214 && g > 214 && b > 214) {
      const minC = Math.min(r, g, b);
      const alpha = Math.round(
        interpolateClamp(minC, 215, 238, 255, 0),
      );
      px[i + 3] = Math.min(px[i + 3], alpha);
    }
  }
  ctx.putImageData(data, 0, 0);
  return canvas.toDataURL("image/png");
}

function interpolateClamp(
  v: number,
  inMin: number,
  inMax: number,
  outMin: number,
  outMax: number,
): number {
  if (v <= inMin) return outMin;
  if (v >= inMax) return outMax;
  const t = (v - inMin) / (inMax - inMin);
  return outMin + t * (outMax - outMin);
}

const WhiteKeyImage: React.FC<{
  src: string;
  style?: React.CSSProperties;
}> = ({ src, style }) => {
  const [resolvedSrc, setResolvedSrc] = useState<string>(
    () => whiteCache.get(src) ?? "",
  );

  useEffect(() => {
    const cached = whiteCache.get(src);
    if (cached) {
      setResolvedSrc(cached);
      return;
    }
    const handle = delayRender(`white-key ${src}`);
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
      let out: string;
      try {
        out = keyOutWhite(img);
      } catch {
        out = src;
      }
      whiteCache.set(src, out);
      setResolvedSrc(out);
      continueRender(handle);
    };
    img.onerror = () => {
      whiteCache.set(src, "");
      setResolvedSrc("");
      continueRender(handle);
    };
    img.src = src;
  }, [src]);

  if (!resolvedSrc) return null;
  return <Img src={resolvedSrc} style={style} />;
};

interface HostProps {
  voiceUrl: string;
  /** 0–1 entrance progress */
  entranceProgress: number;
  /**
   * Absolute frame at which this scene starts within the full composition.
   * Used to sample the correct portion of the continuous narration audio AND
   * to drive the idle-talk glide continuously across the whole video.
   */
  audioFrameOffset?: number;
  /**
   * Optional pose. When omitted or "idle-talk", the Pharaoh glides and lip-
   * syncs to audio. Otherwise renders the matching pose PNG with its own
   * anchor + entry animation.
   */
  pharaohPose?: PharaohPose;
  /** Duration of the scene in frames — used to time walk-out exit animations. */
  sceneDurationFrames?: number;
}

export const Host: React.FC<HostProps> = ({
  voiceUrl,
  entranceProgress,
  audioFrameOffset = 0,
  pharaohPose,
  sceneDurationFrames,
}) => {
  const frame = useCurrentFrame();
  const { fps, width, height } = useVideoConfig();

  const preset = POSE_PRESETS[pharaohPose ?? "idle-talk"];

  // Idle-talk uses the two-frame mouth-swap system. All other poses use a
  // single pose PNG (no mouth swap — the expression is baked in).
  if (!preset.src) {
    return (
      <IdleTalkHost
        voiceUrl={voiceUrl}
        entranceProgress={entranceProgress}
        audioFrameOffset={audioFrameOffset}
        frame={frame}
        fps={fps}
        width={width}
        height={height}
      />
    );
  }

  // ── POSE MODE — render the pose PNG with anchor + entry animation ─────────
  const CAPTION_RESERVED = Math.round(height * 0.165);
  const CHAR_HEIGHT = Math.round(height * 0.22 * preset.scaleMul);
  const CHAR_WIDTH = Math.round(CHAR_HEIGHT * 0.62);

  // Position by anchor
  let baseLeft = 0;
  let baseBottom = CAPTION_RESERVED;
  const SIDE_MARGIN = 40;
  switch (preset.anchor) {
    case "bottom-left":
      baseLeft = SIDE_MARGIN;
      break;
    case "bottom-center":
      baseLeft = (width - CHAR_WIDTH) / 2;
      break;
    case "bottom-right":
      baseLeft = width - CHAR_WIDTH - SIDE_MARGIN;
      break;
    case "edge-left":
      // Peek poses anchor flush to the very edge (no margin) — they're
      // intentionally cropped by the frame edge in the art.
      baseLeft = -CHAR_WIDTH * 0.15; // bleed slightly off-screen
      baseBottom = Math.round(height * 0.32); // higher than the bottom band
      break;
    case "edge-right":
      baseLeft = width - CHAR_WIDTH * 0.85;
      baseBottom = Math.round(height * 0.32);
      break;
    default:
      baseLeft = SIDE_MARGIN;
  }

  // Entry animation deltas
  let entryX = 0;
  let entryY = 0;
  let entryScale = 1;
  let entryOpacity = 1;

  const entrySpring = spring({
    fps,
    frame,
    config: { damping: 14, stiffness: 100 },
    durationInFrames: 22,
  });

  switch (preset.animation) {
    case "slide-from-left":
      entryX = interpolate(entrySpring, [0, 1], [-CHAR_WIDTH, 0]);
      entryOpacity = interpolate(entrySpring, [0, 0.3], [0, 1], {
        extrapolateRight: "clamp",
      });
      break;
    case "slide-from-right":
      entryX = interpolate(entrySpring, [0, 1], [CHAR_WIDTH, 0]);
      entryOpacity = interpolate(entrySpring, [0, 0.3], [0, 1], {
        extrapolateRight: "clamp",
      });
      break;
    case "fade-in":
      entryOpacity = interpolate(entrySpring, [0, 0.5], [0, 1], {
        extrapolateRight: "clamp",
      });
      break;
    case "scale-pop":
      entryScale = entrySpring;
      entryOpacity = interpolate(entrySpring, [0, 0.3], [0, 1], {
        extrapolateRight: "clamp",
      });
      break;
    case "walk-from-left": {
      // Walks across from off-screen left to the bottom-left anchor over
      // 1 second, with a gentle bob.
      const walkDur = fps * 1.0;
      const walkP = interpolateClamp(frame, 0, walkDur, 0, 1);
      entryX = interpolate(walkP, [0, 1], [-CHAR_WIDTH - 60, 0]);
      entryOpacity = interpolate(walkP, [0, 0.2], [0, 1], {
        extrapolateRight: "clamp",
      });
      entryY = -Math.abs(Math.sin((frame / (fps * 0.32)) * Math.PI)) * 7;
      break;
    }
    case "walk-out-right": {
      // Walks out toward right edge in the LAST 1.2s of the scene.
      const exitStart = Math.max(0, (sceneDurationFrames ?? fps * 8) - fps * 1.2);
      const exitDur = fps * 1.2;
      const exitP = interpolateClamp(frame, exitStart, exitStart + exitDur, 0, 1);
      entryX = interpolate(exitP, [0, 1], [0, CHAR_WIDTH + 80]);
      entryOpacity = interpolate(exitP, [0.7, 1], [1, 0], {
        extrapolateLeft: "clamp",
        extrapolateRight: "clamp",
      });
      entryY = -Math.abs(Math.sin((frame / (fps * 0.32)) * Math.PI)) * 7;
      break;
    }
  }

  // Subtle living-character idle — a tiny breath bob even when "static".
  const breathBob = Math.sin((frame / fps) * 1.6 * Math.PI) * 2.4;

  const facing = preset.facing ?? 1;

  return (
    <div
      style={{
        position: "absolute",
        bottom: baseBottom,
        left: baseLeft,
        width: CHAR_WIDTH,
        height: CHAR_HEIGHT,
        transform: [
          `translateX(${entryX}px)`,
          `translateY(${entryY + breathBob}px)`,
          `scale(${entryScale})`,
          `scaleX(${facing})`,
        ].join(" "),
        transformOrigin: "bottom center",
        opacity: entryOpacity,
        filter: "drop-shadow(0 14px 16px rgba(0,0,0,0.5))",
      }}
    >
      <WhiteKeyImage
        src={preset.src}
        style={{
          position: "absolute",
          inset: 0,
          width: "100%",
          height: "100%",
          objectFit: "contain",
          objectPosition: "bottom center",
        }}
      />
    </div>
  );
};

// ─────────────────────────────────────────────────────────────────────────────
// IdleTalkHost — the original two-frame audio-driven Pharaoh, used as the
// default when no pose is specified.
// ─────────────────────────────────────────────────────────────────────────────
interface IdleTalkHostProps {
  voiceUrl: string;
  entranceProgress: number;
  audioFrameOffset: number;
  frame: number;
  fps: number;
  width: number;
  height: number;
}

const IdleTalkHost: React.FC<IdleTalkHostProps> = ({
  voiceUrl,
  entranceProgress,
  audioFrameOffset,
  frame,
  fps,
  width,
  height,
}) => {
  const absoluteFrame = frame + audioFrameOffset;
  const audioData = useAudioData(voiceUrl);

  const speechEnergy: number = useMemo(() => {
    if (!audioData) return 0;
    const amplitudes = visualizeAudio({
      fps,
      frame: absoluteFrame,
      audioData,
      numberOfSamples: 32,
    });
    const speechBins = amplitudes.slice(4, 20);
    return speechBins.reduce((a, b) => a + b, 0) / speechBins.length;
  }, [audioData, absoluteFrame, fps]);

  const CAPTION_RESERVED = Math.round(height * 0.165);
  const CHAR_HEIGHT = Math.round(height * 0.22);
  const CHAR_WIDTH = Math.round(CHAR_HEIGHT * 0.62);

  const SIDE_MARGIN = 40;
  const glideMin = SIDE_MARGIN;
  const glideMax = width - CHAR_WIDTH - SIDE_MARGIN;
  const glidePeriod = fps * 14;
  const glidePhase = Math.sin((absoluteFrame / glidePeriod) * 2 * Math.PI);
  const glideX = interpolate(glidePhase, [-1, 1], [glideMin, glideMax]);

  const movingRight =
    Math.cos((absoluteFrame / glidePeriod) * 2 * Math.PI) >= 0;
  const facing = movingRight ? 1 : -1;

  const stepPeriod = fps * 0.62;
  const stepPhase = (absoluteFrame / stepPeriod) * 2 * Math.PI;
  const walkBob = -Math.abs(Math.sin(stepPhase)) * 9;
  const walkRock = Math.sin(stepPhase) * 2.2;

  const slideY = interpolate(entranceProgress, [0, 1], [120, 0], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const opacity = interpolate(entranceProgress, [0, 0.4], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  const speechBob = -Math.min(speechEnergy, 0.6) * 6;
  const mouthOpen = speechEnergy >= 0.13;

  const frameImgStyle: React.CSSProperties = {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "contain",
    objectPosition: "bottom center",
  };

  return (
    <div
      style={{
        position: "absolute",
        bottom: CAPTION_RESERVED,
        left: 0,
        width: CHAR_WIDTH,
        height: CHAR_HEIGHT,
        transform: [
          `translateX(${glideX}px)`,
          `translateY(${slideY + walkBob + speechBob}px)`,
          `rotate(${walkRock}deg)`,
          `scaleX(${facing})`,
        ].join(" "),
        transformOrigin: "bottom center",
        opacity,
        filter: "drop-shadow(0 14px 16px rgba(0,0,0,0.5))",
      }}
    >
      <WhiteKeyImage
        src={PHARAOH_CLOSED}
        style={{ ...frameImgStyle, opacity: mouthOpen ? 0 : 1 }}
      />
      <WhiteKeyImage
        src={PHARAOH_OPEN}
        style={{ ...frameImgStyle, opacity: mouthOpen ? 1 : 0 }}
      />
    </div>
  );
};
